"""Initial schema setup

Revision ID: 1cf54ddf96d3
Revises: 
Create Date: 2025-11-14 03:44:21.723904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '1cf54ddf96d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('"USER"',
    sa.Column('USER_ID', sa.TEXT(), nullable=False),
    sa.Column('PW', sa.TEXT(), nullable=False),
    sa.Column('NAME', sa.TEXT(), nullable=False),
    sa.Column('EMAIL', sa.TEXT(), nullable=True),
    sa.Column('PHONE', sa.TEXT(), nullable=True),
    sa.Column('JOIN_DT', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('EXT_API_KEY', sa.TEXT(), nullable=True),
    sa.Column('STATUS', sa.TEXT(), nullable=False),
    sa.CheckConstraint('"STATUS" IN (\'A\', \'D\')', name='ck_user_status'),
    sa.PrimaryKeyConstraint('USER_ID'),
    sa.UniqueConstraint('EMAIL')
    )
    op.create_table('KEYWORD_BOOST_DICT',
    sa.Column('KEY_ID', sa.TEXT(), nullable=False),
    sa.Column('USER_ID', sa.TEXT(), nullable=False),
    sa.Column('KEYWORD', sa.TEXT(), nullable=False),
    sa.Column('CATEGORY', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['USER_ID'], ['"USER".USER_ID'], ),
    sa.PrimaryKeyConstraint('KEY_ID')
    )
    op.create_table('KNOWLEDGE_SOURCE',
    sa.Column('SRC_ID', sa.TEXT(), nullable=False),
    sa.Column('OWNER_ID', sa.TEXT(), nullable=False),
    sa.Column('SRC_TYPE', sa.TEXT(), nullable=False),
    sa.Column('TITLE', sa.TEXT(), nullable=True),
    sa.Column('SRC_PATH', sa.TEXT(), nullable=True),
    sa.Column('META_JSON', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('CREATED_DT', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['OWNER_ID'], ['"USER".USER_ID'], ),
    sa.PrimaryKeyConstraint('SRC_ID')
    )
    op.create_table('MEETING',
    sa.Column('MEETING_ID', sa.TEXT(), nullable=False),
    sa.Column('TITLE', sa.TEXT(), nullable=True),
    sa.Column('PURPOSE', sa.TEXT(), nullable=True),
    sa.Column('START_DT', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('END_DT', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('CREATOR_ID', sa.TEXT(), nullable=False),
    sa.Column('LOCATION', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['CREATOR_ID'], ['"USER".USER_ID'], ),
    sa.PrimaryKeyConstraint('MEETING_ID')
    )
    op.create_table('USER_SETTING',
    sa.Column('SETTING_ID', sa.TEXT(), nullable=False),
    sa.Column('USER_ID', sa.TEXT(), nullable=False),
    sa.Column('MEETING_TEMPLATE_ID', sa.TEXT(), nullable=True),
    sa.Column('BOOST_USE_YN', sa.TEXT(), nullable=False),
    sa.CheckConstraint('"BOOST_USE_YN" IN (\'Y\', \'N\')', name='ck_user_setting_boost_yn'),
    sa.ForeignKeyConstraint(['USER_ID'], ['"USER".USER_ID'], ),
    sa.PrimaryKeyConstraint('SETTING_ID')
    )
    op.create_table('ACTION_ITEM',
    sa.Column('ITEM_ID', sa.TEXT(), nullable=False),
    sa.Column('MEETING_ID', sa.TEXT(), nullable=False),
    sa.Column('TITLE', sa.TEXT(), nullable=False),
    sa.Column('DESCRIPTION', sa.TEXT(), nullable=True),
    sa.Column('DUE_DT', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('PRIORITY', sa.TEXT(), nullable=True),
    sa.Column('EXTERNAL_TOOL', sa.TEXT(), nullable=True),
    sa.Column('STATUS', sa.TEXT(), nullable=False),
    sa.Column('CREATED_DT', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UPDATED_DT', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['MEETING_ID'], ['MEETING.MEETING_ID'], ),
    sa.PrimaryKeyConstraint('ITEM_ID')
    )
    op.create_table('ARTIFACT_LOG',
    sa.Column('ARTIFACT_LOG_ID', sa.TEXT(), nullable=False),
    sa.Column('MEETING_ID', sa.TEXT(), nullable=False),
    sa.Column('ARTIFACT_TYPE', sa.TEXT(), nullable=False),
    sa.Column('ARTIFACT_PATH', sa.TEXT(), nullable=True),
    sa.Column('TARGET', sa.TEXT(), nullable=True),
    sa.Column('RESULT', sa.TEXT(), nullable=True),
    sa.Column('CREATED_DT', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['MEETING_ID'], ['MEETING.MEETING_ID'], ),
    sa.PrimaryKeyConstraint('ARTIFACT_LOG_ID')
    )
    op.create_table('CHATBOT_LOG',
    sa.Column('LOG_ID', sa.TEXT(), nullable=False),
    sa.Column('MEETING_ID', sa.TEXT(), nullable=False),
    sa.Column('USER_ID', sa.TEXT(), nullable=False),
    sa.Column('Q_TEXT', sa.TEXT(), nullable=False),
    sa.Column('A_TEXT', sa.TEXT(), nullable=True),
    sa.Column('ASKED_DT', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['MEETING_ID'], ['MEETING.MEETING_ID'], ),
    sa.ForeignKeyConstraint(['USER_ID'], ['"USER".USER_ID'], ),
    sa.PrimaryKeyConstraint('LOG_ID')
    )
    op.create_table('STT_CHUNK',
    sa.Column('CHUNK_ID', sa.TEXT(), nullable=False),
    sa.Column('MEETING_ID', sa.TEXT(), nullable=False),
    sa.Column('UTTER_ID', sa.TEXT(), nullable=True),
    sa.Column('START_SEC', sa.Float(), nullable=False),
    sa.Column('END_SEC', sa.Float(), nullable=False),
    sa.Column('SPEAKER_LABEL', sa.TEXT(), nullable=True),
    sa.Column('TEXT', sa.TEXT(), nullable=False),
    sa.Column('text_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('CREATED_DT', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['MEETING_ID'], ['MEETING.MEETING_ID'], ),
    sa.PrimaryKeyConstraint('CHUNK_ID')
    )
    op.create_table('SUMMARY',
    sa.Column('SUMMARY_ID', sa.TEXT(), nullable=False),
    sa.Column('MEETING_ID', sa.TEXT(), nullable=False),
    sa.Column('FORMAT', sa.TEXT(), nullable=False),
    sa.Column('CONTENT', sa.TEXT(), nullable=False),
    sa.Column('PROMPT_ID', sa.TEXT(), nullable=True),
    sa.Column('CREATED_DT', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['MEETING_ID'], ['MEETING.MEETING_ID'], ),
    sa.PrimaryKeyConstraint('SUMMARY_ID')
    )
    op.create_table('FINAL_ANALYSIS',
    sa.Column('FINAL_ID', sa.TEXT(), nullable=False),
    sa.Column('MEETING_ID', sa.TEXT(), nullable=False),
    sa.Column('FINAL_TYPE', sa.TEXT(), nullable=False),
    sa.Column('SUMMARY_ID', sa.TEXT(), nullable=True),
    sa.Column('CONTENT', sa.TEXT(), nullable=False),
    sa.Column('ARTIFACT_PATH', sa.TEXT(), nullable=True),
    sa.Column('CREATED_DT', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['MEETING_ID'], ['MEETING.MEETING_ID'], ),
    sa.ForeignKeyConstraint(['SUMMARY_ID'], ['SUMMARY.SUMMARY_ID'], ),
    sa.PrimaryKeyConstraint('FINAL_ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FINAL_ANALYSIS')
    op.drop_table('SUMMARY')
    op.drop_table('STT_CHUNK')
    op.drop_table('CHATBOT_LOG')
    op.drop_table('ARTIFACT_LOG')
    op.drop_table('ACTION_ITEM')
    op.drop_table('USER_SETTING')
    op.drop_table('MEETING')
    op.drop_table('KNOWLEDGE_SOURCE')
    op.drop_table('KEYWORD_BOOST_DICT')
    op.drop_table('"USER"')
    # ### end Alembic commands ###
