"""add content and summary fields to meeting table

Revision ID: 7e28e15cd9cf
Revises: b8d1b39e338f
Create Date: 2025-11-20 04:49:48.237802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e28e15cd9cf'
down_revision: Union[str, Sequence[str], None] = 'b8d1b39e338f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MEETING', sa.Column('CONTENT', sa.TEXT(), nullable=True))
    op.add_column('MEETING', sa.Column('AI_SUMMARY', sa.TEXT(), nullable=True))
    op.add_column('MEETING', sa.Column('PARTICIPANTS', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('MEETING', sa.Column('KEY_DECISIONS', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('MEETING', sa.Column('NEXT_STEPS', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('MEETING', sa.Column('AUDIO_URL', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MEETING', 'AUDIO_URL')
    op.drop_column('MEETING', 'NEXT_STEPS')
    op.drop_column('MEETING', 'KEY_DECISIONS')
    op.drop_column('MEETING', 'PARTICIPANTS')
    op.drop_column('MEETING', 'AI_SUMMARY')
    op.drop_column('MEETING', 'CONTENT')
    # ### end Alembic commands ###
