"""Fix ForeignKey for Meeting.creator_id

Revision ID: b8d1b39e338f
Revises: 811da328b9eb
Create Date: 2025-11-20 01:38:40.899016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'b8d1b39e338f'
down_revision: Union[str, Sequence[str], None] = '811da328b9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EMBEDDING',
    sa.Column('EMBEDDING_ID', sa.TEXT(), nullable=False),
    sa.Column('MEETING_ID', sa.TEXT(), nullable=False),
    sa.Column('CHUNK_TEXT', sa.TEXT(), nullable=False),
    sa.Column('EMBEDDING', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('CREATED_DT', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['MEETING_ID'], ['MEETING.MEETING_ID'], ),
    sa.PrimaryKeyConstraint('EMBEDDING_ID')
    )
    op.add_column('ACTION_ITEM', sa.Column('ASSIGNEE_ID', sa.TEXT(), nullable=True))
    op.create_foreign_key(None, 'ACTION_ITEM', 'RN_USER', ['ASSIGNEE_ID'], ['USER_ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ACTION_ITEM', type_='foreignkey')
    op.drop_column('ACTION_ITEM', 'ASSIGNEE_ID')
    op.drop_table('EMBEDDING')
    # ### end Alembic commands ###
